"""tests/test_lessons_delivery.py — the shared gotchas reach every project.

The baseline's index said "read `docs/gotchas/x.md`" while nothing ever put those
files in a project (measured on Fortuna Lab: a `project-baseline.md`, no gotchas).
Everything here pins a way that delivery could go wrong WITHOUT anything raising:
a lesson silently missing, a hand edit overwritten, a copy attributed to the wrong
source, a delivered file left public in a repository that keeps its instructions
private, or one bad file stopping the other fifteen.
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
import types

import pytest

from helpers import baseline_copy as bc
from helpers import ignore_alignment as ia
from helpers import instructions_posture as ip
from helpers import instructions_wiring as iw
from helpers import lessons_delivery as ld
from helpers import managed_copy as mc
from helpers.instructions_posture import canonical

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES = os.path.join(REPO_ROOT, "templates")

GIT = shutil.which("git") or ""
needs_git = pytest.mark.skipif(not GIT, reason="git not installed")

BASELINE_TEXT = "# Project Baseline Rules\n\n## Tokensave: Use It First\n"


def _corpus(**overrides):
    """A tiny in-memory corpus: real specs, invented text, optional overrides."""
    return tuple(ld.Lesson(spec, overrides.get(spec.source_rel,
                                               "# %s\n\nbody\n" % spec.source_rel))
                 for spec in ld.LESSONS)


def _dest(root, rel):
    return os.path.join(str(root), *rel.split("/"))


# ── the inventory is explicit, and matches what actually ships ────────────

def test_the_inventory_names_every_template_lesson_and_nothing_else():
    """A new file in templates/gotchas/ must be a decision, not a side effect."""
    on_disk = {"gotchas/" + n for n in os.listdir(os.path.join(TEMPLATES, "gotchas"))
               if n.endswith(".md")} | {"NUITKA_GOTCHAS.md"}
    assert {s.source_rel for s in ld.LESSONS} == on_disk


def test_every_source_exists_and_is_non_empty():
    corpus = ld.load_corpus(TEMPLATES)
    assert all(lesson.text for lesson in corpus), \
        [l.spec.source_rel for l in corpus if not l.text]


def test_destinations_are_unique_fixed_and_inside_docs_gotchas():
    dests = ld.dest_rels()
    assert len(set(dests)) == len(dests)
    assert all(d.startswith(ld.GOTCHA_DIR + "/") and ".." not in d
               and not os.path.isabs(d) and "\\" not in d for d in dests)
    assert len({s.source_rel for s in ld.LESSONS}) == len(ld.LESSONS)


def test_every_path_the_baseline_index_names_is_delivered_and_vice_versa():
    """The link the whole feature exists for: what the index says to read must
    be a file a project actually receives."""
    text = open(os.path.join(TEMPLATES, "project-baseline.md"),
                encoding="utf-8").read()
    named = set(re.findall(r"`(docs/gotchas/[^`]+\.md)`", text))
    assert named == set(ld.dest_rels()), (
        "index names but not delivered: %s; delivered but not indexed: %s"
        % (sorted(named - set(ld.dest_rels())),
           sorted(set(ld.dest_rels()) - named)))
    assert "`gotchas/" not in text, "an index path still points at the old layout"


# ── managed copies: identity is the source, not only the hash ─────────────

def test_the_header_records_the_source_and_reads_it_back():
    text = mc.render_copy("body\n", "gotchas/a.md")
    facts = mc.parse_copy(text, "gotchas/a.md")
    assert facts.header == mc.HEADER_OK and facts.source_id == "gotchas/a.md"


def test_identical_bodies_from_different_sources_are_not_interchangeable(tmp_path):
    """Two lessons may share a body; a hash alone could not tell them apart."""
    body = "same body\n"
    path = tmp_path / "docs" / "gotchas" / "a.md"
    path.parent.mkdir(parents=True)
    path.write_text(mc.render_copy(body, "gotchas/b.md"), encoding="utf-8")

    result = mc.write_managed(
        str(tmp_path), mc.ManagedCopySpec("docs/gotchas/a.md", "gotchas/a.md", body))

    assert result.ok is False and result.state_before == mc.COPY_INVALID
    assert "b.md" in path.read_text(encoding="utf-8"), "was overwritten"


def test_a_baseline_header_written_before_this_change_is_still_current():
    """Every project in the fleet carries the old spelling; it must not go
    stale merely because the grammar became general."""
    legacy = ("<!-- tokensave-manager:copy project-baseline.md sha256=%s "
              "- generated by TokenSave Manager; edit the template there, not "
              "this file -->\n%s" % (mc.content_sha(BASELINE_TEXT), BASELINE_TEXT))
    facts = bc.parse_copy(legacy)
    assert bc.classify_copy(facts, bc.content_sha(BASELINE_TEXT)) == bc.COPY_CURRENT


def test_a_header_naming_another_source_is_invalid_for_the_baseline_too():
    other = mc.render_copy(BASELINE_TEXT, "gotchas/x.md")
    assert bc.parse_copy(other).header == bc.HEADER_INVALID


# ── delivery: per artifact, never a transaction ───────────────────────────

def test_a_fresh_project_receives_every_lesson_and_reads_back_current(tmp_path):
    corpus = _corpus()
    outcomes = ld.sync_lessons(str(tmp_path), corpus)

    assert {o.outcome for o in outcomes} == {ld.OUT_WRITTEN}
    assert len(outcomes) == len(ld.LESSONS)
    assert {f.state for f in ld.read_lessons(str(tmp_path), corpus)} == \
        {mc.COPY_CURRENT}


def test_a_second_run_changes_nothing(tmp_path):
    corpus = _corpus()
    ld.sync_lessons(str(tmp_path), corpus)
    before = {r: open(_dest(tmp_path, r), "rb").read() for r in ld.dest_rels()}
    again = ld.sync_lessons(str(tmp_path), corpus)
    assert {o.outcome for o in again} == {ld.OUT_CURRENT}
    assert ld.written_files(again) == ()
    assert {r: open(_dest(tmp_path, r), "rb").read()
            for r in ld.dest_rels()} == before


def test_an_outdated_lesson_is_refreshed(tmp_path):
    target = ld.LESSONS[0]
    ld.sync_lessons(str(tmp_path), _corpus())
    newer = _corpus(**{target.source_rel: "# newer\n"})
    outcomes = {o.dest_rel: o for o in ld.sync_lessons(str(tmp_path), newer)}
    assert outcomes[target.dest_rel].outcome == ld.OUT_WRITTEN
    assert outcomes[target.dest_rel].state_before == mc.COPY_OUTDATED
    assert "# newer" in open(_dest(tmp_path, target.dest_rel),
                             encoding="utf-8").read()


def test_the_fleet_case_unchanged_edited_and_missing_are_each_handled(tmp_path):
    """A is current, B has a hand edit, C lacks one. Each is its own result."""
    corpus = _corpus()
    a, b, c = (tmp_path / n for n in "abc")
    for root in (a, b, c):
        ld.sync_lessons(str(root), corpus)

    edited_rel, missing_rel = ld.dest_rels()[1], ld.dest_rels()[2]
    edited = _dest(b, edited_rel)
    with open(edited, "a", encoding="utf-8") as fh:
        fh.write("\nMY OWN NOTE\n")
    edited_bytes = open(edited, "rb").read()
    os.remove(_dest(c, missing_rel))

    out_a = ld.sync_lessons(str(a), corpus)
    out_b = {o.dest_rel: o for o in ld.sync_lessons(str(b), corpus)}
    out_c = {o.dest_rel: o for o in ld.sync_lessons(str(c), corpus)}

    assert {o.outcome for o in out_a} == {ld.OUT_CURRENT}
    assert out_b[edited_rel].outcome == ld.OUT_REFUSED
    assert out_b[edited_rel].state_before == mc.COPY_EDITED
    assert open(edited, "rb").read() == edited_bytes, "a hand edit was overwritten"
    assert sum(o.outcome == ld.OUT_CURRENT for o in out_b.values()) == \
        len(ld.LESSONS) - 1, "one refusal must not stop the others"
    assert out_c[missing_rel].outcome == ld.OUT_WRITTEN
    assert os.path.isfile(_dest(c, missing_rel))


def test_one_unreadable_destination_does_not_stop_the_rest(tmp_path):
    """A directory where a lesson should be: unreadable, and not ours to touch."""
    blocked = ld.dest_rels()[0]
    os.makedirs(_dest(tmp_path, blocked))
    outcomes = {o.dest_rel: o for o in ld.sync_lessons(str(tmp_path), _corpus())}

    assert outcomes[blocked].outcome == ld.OUT_REFUSED
    assert outcomes[blocked].state_before == mc.COPY_UNREADABLE
    assert sum(o.outcome == ld.OUT_WRITTEN for o in outcomes.values()) == \
        len(ld.LESSONS) - 1
    assert "1 refused" in ld.outcomes_text(outcomes.values())


def test_an_unreadable_source_is_reported_per_artifact_not_dropped(tmp_path):
    lost = ld.LESSONS[3]
    outcomes = {o.dest_rel: o for o in ld.sync_lessons(
        str(tmp_path), _corpus(**{lost.source_rel: ""}))}
    assert outcomes[lost.dest_rel].outcome == ld.OUT_FAILED
    assert "could not be read" in outcomes[lost.dest_rel].reason
    assert not os.path.exists(_dest(tmp_path, lost.dest_rel))
    facts = {f.dest_rel: f for f in ld.read_lessons(
        str(tmp_path), _corpus(**{lost.source_rel: ""}))}
    assert facts[lost.dest_rel].state == ld.STATE_SOURCE_UNREADABLE


def test_files_the_corpus_does_not_name_are_never_touched_or_deleted(tmp_path):
    stray = tmp_path / "docs" / "gotchas" / "removed-from-templates.md"
    stray.parent.mkdir(parents=True)
    stray.write_text("kept\n", encoding="utf-8")
    ld.sync_lessons(str(tmp_path), _corpus())
    assert stray.read_text(encoding="utf-8") == "kept\n"


def test_a_person_owned_file_at_a_lesson_path_is_refused_untouched(tmp_path):
    rel = ld.dest_rels()[0]
    path = _dest(tmp_path, rel)
    os.makedirs(os.path.dirname(path))
    open(path, "w", encoding="utf-8").write("# my own gotchas\n")
    out = {o.dest_rel: o for o in ld.sync_lessons(str(tmp_path), _corpus())}
    assert out[rel].outcome == ld.OUT_REFUSED
    assert out[rel].state_before == mc.COPY_UNMANAGED
    assert open(path, encoding="utf-8").read() == "# my own gotchas\n"


def test_summaries_read_in_a_fixed_order_and_omit_zeros():
    assert ld.summarize(["current"] * 11 + ["outdated"]) == "11 current, 1 outdated"
    assert ld.summarize([]) == "none"
    assert "source unreadable" in ld.summarize([ld.STATE_SOURCE_UNREADABLE])


# ── who receives them ─────────────────────────────────────────────────────

def _posture(root, reach=ip.REACH_RESOLVED, copy=bc.COPY_CURRENT):
    return types.SimpleNamespace(display_root=str(root), reach=reach,
                                 copy_state=copy)


def test_only_a_project_with_a_current_resolving_baseline_receives_lessons(tmp_path):
    corpus = _corpus()
    assert iw.deliver_lessons(_posture(tmp_path, reach=ip.REACH_ORPHANED), corpus) == ()
    assert iw.deliver_lessons(_posture(tmp_path, copy=bc.COPY_OUTDATED), corpus) == ()
    assert iw.deliver_lessons(_posture(tmp_path), None) == ()
    assert not os.path.exists(os.path.join(str(tmp_path), "docs"))
    assert len(iw.deliver_lessons(_posture(tmp_path), corpus)) == len(ld.LESSONS)


def test_an_outcome_reports_lessons_as_their_own_dimension():
    outcomes = (ld.LessonOutcome("docs/gotchas/a.md", ld.OUT_WRITTEN),
                ld.LessonOutcome("docs/gotchas/b.md", ld.OUT_REFUSED, "edited",
                                 "docs/gotchas/b.md is edited - not overwritten"))
    result = iw.ApplyOutcome(iw.OUTCOME_ALREADY_RESOLVED, lessons=outcomes)
    text = result.render()
    assert "instructions: already resolved" in text
    assert "lessons: 1 written, 1 refused" in text
    assert result.lesson_files == ("docs/gotchas/a.md",)
    assert result.mutated and result.wrote is False
    # No corpus given: exactly the sentence it always was.
    assert iw.ApplyOutcome(iw.OUTCOME_WIRED).render() == "wired"


# -- the wiring path, against a real project on disk -------------------------

@pytest.fixture
def templates(tmp_path):
    d = tmp_path / "templates"
    d.mkdir()
    (d / "project-baseline.md").write_text(BASELINE_TEXT, encoding="utf-8")
    return d


def _project(tmp_path, templates, name="proj"):
    root = tmp_path / name
    root.mkdir()
    (root / "CLAUDE.md").write_text("@BASIC_INSTRUCTIONS.md\n", encoding="utf-8")
    (root / "BASIC_INSTRUCTIONS.md").write_text(bc.LOCAL_INCLUDE_LINE + "\n",
                                                encoding="utf-8")
    (root / "project-baseline.md").write_bytes(
        bc.render_copy(BASELINE_TEXT).encode("utf-8"))
    return root


def _posture_of(root, templates):
    return ip.read_project(
        str(root), root.name, str(templates),
        ip.canonical(str(templates / "project-baseline.md")), BASELINE_TEXT, "", {})


def _apply(root, templates, lessons, git_exe=""):
    return iw.apply_to_project(
        _posture_of(root, templates),
        ip.canonical(str(templates / "project-baseline.md")), str(templates),
        "", False, BASELINE_TEXT, claude_projects={}, git_exe=git_exe,
        lessons=lessons)


def test_an_already_wired_project_receives_the_lessons_through_the_normal_apply(
        tmp_path, templates):
    root = _project(tmp_path, templates)
    result = _apply(root, templates, _corpus())
    assert result.outcome == iw.OUTCOME_ALREADY_RESOLVED
    assert {o.outcome for o in result.lessons} == {ld.OUT_WRITTEN}
    assert result.mutated
    for rel in ld.dest_rels():
        assert os.path.isfile(_dest(root, rel))


def test_the_delivered_path_resolves_from_the_project_root(tmp_path, templates):
    """The link, not merely file presence: every path the baseline index names
    must open from the project root after delivery."""
    root = _project(tmp_path, templates)
    _apply(root, templates, ld.load_corpus(TEMPLATES))
    index = open(os.path.join(TEMPLATES, "project-baseline.md"),
                 encoding="utf-8").read()
    for rel in set(re.findall(r"`(docs/gotchas/[^`]+\.md)`", index)):
        path = _dest(root, rel)
        assert os.path.isfile(path), rel
        assert open(path, encoding="utf-8").readline().startswith(
            "<!-- tokensave-manager:copy ")


def test_an_excluded_project_gets_neither_the_baseline_nor_the_lessons(
        tmp_path, templates, monkeypatch):
    """A skipped project must never hold a baseline whose index points at files
    that were withheld."""
    import dataclasses
    root = _project(tmp_path, templates)
    posture = dataclasses.replace(_posture_of(root, templates), excluded=True,
                                  exclude_reason="vendor clone")
    monkeypatch.setattr(ip, "read_project",
                        lambda *a, **k: posture)
    result = iw.apply_to_project(
        posture, ip.canonical(str(templates / "project-baseline.md")),
        str(templates), "", False, BASELINE_TEXT, claude_projects={},
        lessons=_corpus())
    assert result.outcome == iw.OUTCOME_SKIPPED_BLOCKED
    assert result.lessons == ()
    assert not os.path.exists(os.path.join(str(root), "docs"))


# ── git alignment: the third level of the chain ───────────────────────────

COPY = bc.COPY_BASENAME
GOTCHA = ld.dest_rels()[0]


def _pair(rel, referrer=COPY):
    return ia.CompanionPair(rel, referrer, ia.KIND_GOTCHA)


def _facts(ref_git, comp_git, comp_fs=ia.FS_EXISTS, repo=ia.REPO):
    return ia.Facts(repo, {COPY: ia.PathFact(ia.FS_EXISTS, ref_git),
                           GOTCHA: ia.PathFact(comp_fs, comp_git)})


@pytest.mark.parametrize("ref,comp,pending", [
    (ia.LOCAL, ia.LOCAL, False),      # already aligned
    (ia.LOCAL, ia.OPEN, True),        # the KicomAI bug, one level down
    (ia.OPEN, ia.OPEN, False),
    (ia.TRACKED, ia.OPEN, False),     # both will be committed together
    (ia.TRACKED, ia.TRACKED, False),
])
def test_gotcha_alignment_table(ref, comp, pending):
    result = ia.decide([_pair(GOTCHA)], _facts(ref, comp))
    assert bool(result.pending) is pending
    assert not result.unknown


def test_a_visible_referrer_with_an_ignored_lesson_is_only_a_note():
    result = ia.decide([_pair(GOTCHA)], _facts(ia.TRACKED, ia.LOCAL))
    assert result.pending == () and result.notes


def test_a_tracked_lesson_under_a_local_referrer_is_reported_never_untracked():
    result = ia.decide([_pair(GOTCHA)], _facts(ia.LOCAL, ia.TRACKED))
    assert result.pending == ()
    assert "git rm --cached" in result.notes[0]


@pytest.mark.parametrize("ref,comp", [(ia.UNKNOWN, ia.OPEN), (ia.LOCAL, ia.UNKNOWN)])
def test_unknown_is_never_acted_on_for_lessons(ref, comp):
    result = ia.decide([_pair(GOTCHA)], _facts(ref, comp))
    assert result.pending == () and result.unknown


def _chain(root, files):
    return types.SimpleNamespace(
        display_root=str(root),
        chain=tuple(canonical(os.path.join(str(root), f)) for f in files),
        baseline_directives=(("BASIC_INSTRUCTIONS.md", 1, COPY),))


def test_lessons_are_companions_of_the_baseline_copy_and_only_when_present(tmp_path):
    posture = _chain(tmp_path, ["CLAUDE.md", "BASIC_INSTRUCTIONS.md", COPY])
    assert not [p for p in ia.companions_of(posture)
                if p.kind == ia.KIND_GOTCHA]
    ld.sync_lessons(str(tmp_path), _corpus())
    pairs = [p for p in ia.companions_of(posture) if p.kind == ia.KIND_GOTCHA]
    assert {p.companion_rel for p in pairs} == set(ld.dest_rels())
    assert {p.referrer_rel for p in pairs} == {COPY}


def test_without_the_baseline_copy_in_the_chain_nothing_refers_to_the_lessons(
        tmp_path):
    ld.sync_lessons(str(tmp_path), _corpus())
    posture = _chain(tmp_path, ["CLAUDE.md"])
    assert not [p for p in ia.companions_of(posture)
                if p.kind == ia.KIND_GOTCHA]


def _run(root, *args):
    return subprocess.run([GIT, "-C", str(root)] + list(args), check=True,
                          capture_output=True, text=True)


def _local_only_repo(root, ignore="CLAUDE.md\nBASIC_INSTRUCTIONS.md\n"):
    _run(root, "init", "-q")
    _run(root, "config", "user.email", "t@example.com")
    _run(root, "config", "user.name", "t")
    (root / ".gitignore").write_text(ignore, encoding="utf-8")
    _run(root, "add", ".gitignore")
    _run(root, "commit", "-q", "-m", "init")


@needs_git
def test_a_local_only_project_ignores_the_lessons_through_all_three_levels(
        tmp_path, templates):
    """KicomAI's shape. CLAUDE.md and BASIC are ignored; the baseline copy and
    every lesson must end up ignored too, in ONE apply, or the next commit
    publishes files whose referrer is private."""
    root = _project(tmp_path, templates)
    _local_only_repo(root)

    result = _apply(root, templates, _corpus(), git_exe=GIT)

    porcelain = _run(root, "status", "--porcelain", "--untracked-files=all").stdout
    assert porcelain.strip() == "M .gitignore", porcelain
    assert result.alignment.unconfirmed == ()
    confirmed = {p.companion_rel for p in result.alignment.confirmed}
    assert set(ld.dest_rels()) <= confirmed
    assert COPY in confirmed


@needs_git
def test_a_tracked_referrer_leaves_the_lessons_open_and_writes_no_gitignore_rule(
        tmp_path, templates):
    root = _project(tmp_path, templates)
    _local_only_repo(root, ignore="# nothing local\n")
    result = _apply(root, templates, _corpus(), git_exe=GIT)
    assert result.alignment is None or result.alignment.confirmed == ()
    assert "docs/gotchas" not in (root / ".gitignore").read_text(encoding="utf-8")


# ── the overview reads the same facts ─────────────────────────────────────

def test_the_overview_only_reads_lessons_for_projects_that_hold_a_current_baseline(
        tmp_path):
    from dialogs import instructions_overview as io_

    good, orphan, out = (tmp_path / n for n in ("good", "orphan", "out"))
    for d in (good, orphan, out):
        d.mkdir()

    def proj(d, **kw):
        base = dict(root=str(d), display_root=str(d), excluded=False,
                    reach=ip.REACH_RESOLVED, copy_state=bc.COPY_CURRENT)
        base.update(kw)
        return types.SimpleNamespace(**base)

    fleet = types.SimpleNamespace(projects=[
        proj(good), proj(orphan, reach=ip.REACH_ORPHANED), proj(out, excluded=True)])
    facts = io_._read_lessons(fleet, TEMPLATES)

    assert list(facts) == [str(good)]
    assert {f.state for f in facts[str(good)]} == {mc.COPY_ABSENT}


def test_the_lessons_line_is_its_own_fact_with_honest_colours():
    from dialogs import instructions_overview as io_

    def fact(state):
        return ld.LessonFact("d", "s", state)

    assert io_._lessons_line(()) == ("", "")
    text, colour = io_._lessons_line([fact(mc.COPY_CURRENT)] * 3)
    assert text == "lessons: 3 current" and colour == "overlay0"
    assert io_._lessons_line([fact(mc.COPY_CURRENT), fact(mc.COPY_ABSENT)])[1] == "yellow"
    assert io_._lessons_line([fact(mc.COPY_EDITED)])[1] == "peach"
