"""baseline_copy — the per-project copy of the shared baseline.

## Why a copy, and not the include every project used to carry

Projects included the baseline by absolute path into `template_dir`. Claude
Code does not load an include from outside the project until a person approves
external includes for that project, and the desktop Code tab never asks.
Measured 2026-09-13 on three projects: the flag was `false` everywhere, the
session transcripts' instruction lists stopped at `BASIC_INSTRUCTIONS.md`, and a
canary placed in an external include appeared only after the flag was set by
hand. The baseline had reached no session at all while the Instructions panel
said "chain resolves".

So each project carries `<root>/project-baseline.md`, committed, which also
makes worktrees carry it. The template in `template_dir` stays the one file a
person edits; this module renders, reads and judges the copies.

## Identity is content, and the header only records a claim

Line one is a provenance header with the sha256 of the template body it was
rendered from. Three hashes, one definition (`lf` then sha256 of UTF-8):

    body_sha      the copy's text after line one
    recorded_sha  the hex written in the header
    template_sha  the template as it is now

`recorded != body` means someone edited the copy; `recorded != template` means
the template moved on. Line endings are normalised first, so a CRLF checkout of
an LF render is still current.

**The header grammar is strict.** A file whose first line merely mentions the
marker is not Manager-owned, and a header that starts like ours but does not
parse is `COPY_INVALID` rather than `COPY_UNMANAGED`: a damaged Manager file
must not be indistinguishable from a person's own file, and neither is ever
overwritten.
"""

from __future__ import annotations

import hashlib
import os
import re
from dataclasses import dataclass

from helpers.io_utils import _atomic_write

COPY_BASENAME = "project-baseline.md"
#: The include line a localized `BASIC_INSTRUCTIONS.md` carries.
LOCAL_INCLUDE_LINE = "@" + COPY_BASENAME

_HEADER_PREFIX = "<!-- tokensave-manager:copy"
_HEADER_RE = re.compile(
    r"^<!-- tokensave-manager:copy project-baseline\.md "
    r"sha256=([0-9a-f]{64})(?: [^\r\n]*)? -->$")
_HEADER_NOTE = "- generated by TokenSave Manager; edit the template there, not this file"

COPY_ABSENT = "absent"
COPY_CURRENT = "current"
COPY_OUTDATED = "outdated"
COPY_EDITED = "edited"
COPY_INVALID = "invalid"
COPY_UNMANAGED = "unmanaged"
COPY_UNREADABLE = "unreadable"

#: States a write may replace. Everything else belongs to a person, or is a
#: file we cannot read and so cannot judge.
_WRITABLE = (COPY_ABSENT, COPY_OUTDATED)

HEADER_OK = "ok"
HEADER_INVALID = "invalid"
HEADER_ABSENT = "absent"


def lf(text: str) -> str:
    """LF-normalised. The one normalisation every hash here goes through."""
    return (text or "").replace("\r\n", "\n").replace("\r", "\n")


def content_sha(text: str) -> str:
    return hashlib.sha256(lf(text).encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class CopyFacts:
    """What one file says about itself. Knows nothing about the template."""

    exists: bool = False
    readable: bool = False
    header: str = HEADER_ABSENT
    recorded_sha: str = ""
    body_sha: str = ""
    text: str = ""


def _split_first_line(text: str) -> "tuple[str, str]":
    """(line one without its terminator, everything after the terminator)."""
    for index, char in enumerate(text):
        if char == "\n":
            line = text[:index]
            if line.endswith("\r"):
                line = line[:-1]
            return line, text[index + 1:]
        if char == "\r" and not text.startswith("\n", index + 1):
            return text[:index], text[index + 1:]
    return text, ""


def parse_copy(text: str) -> CopyFacts:
    """Facts from a file's text. Pure."""
    first, body = _split_first_line(text)
    match = _HEADER_RE.match(first)
    if match:
        return CopyFacts(exists=True, readable=True, header=HEADER_OK,
                         recorded_sha=match.group(1), body_sha=content_sha(body),
                         text=text)
    header = HEADER_INVALID if first.startswith(_HEADER_PREFIX) else HEADER_ABSENT
    return CopyFacts(exists=True, readable=True, header=header, text=text)


def read_copy(path: str) -> CopyFacts:
    """Facts about the file at *path*. Reads that one file and nothing else."""
    if not os.path.lexists(path):
        return CopyFacts()
    try:
        with open(path, encoding="utf-8", newline="") as handle:
            text = handle.read()
    except (OSError, UnicodeDecodeError):
        return CopyFacts(exists=True)
    return parse_copy(text)


def classify_copy(facts: CopyFacts, template_sha: str) -> str:
    """The copy's state against the template as it is now. Pure."""
    if not facts.exists:
        return COPY_ABSENT
    if not facts.readable:
        return COPY_UNREADABLE
    if facts.header == HEADER_ABSENT:
        return COPY_UNMANAGED
    if facts.header == HEADER_INVALID:
        return COPY_INVALID
    if facts.body_sha != facts.recorded_sha:
        return COPY_EDITED
    if facts.recorded_sha == template_sha:
        return COPY_CURRENT
    return COPY_OUTDATED


def _dominant_newline(text: str) -> str:
    crlf = text.count("\r\n")
    return "\r\n" if crlf > text.count("\n") - crlf else "\n"


def render_copy(template_text: str) -> str:
    """The exact bytes a copy of *template_text* holds. Deterministic."""
    header = "%s project-baseline.md sha256=%s %s -->" % (
        _HEADER_PREFIX, content_sha(template_text), _HEADER_NOTE)
    return header + _dominant_newline(template_text) + template_text


@dataclass(frozen=True)
class CopyWrite:
    ok: bool
    changed: bool = False
    state_before: str = ""
    error: str = ""


def write_copy(project_root: str, template_text: str,
               expect_recorded_sha: "str | None" = None) -> CopyWrite:
    """Create or refresh `<root>/project-baseline.md`, then verify it.

    Compare-and-apply: the state is re-read here rather than trusted from a
    plan, and *expect_recorded_sha* (for a refresh) must still be what the file
    records. Only an absent or outdated copy is written; a copy that is already
    current is left byte-for-byte alone, which is what keeps a re-run from
    churning a committed file.
    """
    if not template_text:
        return CopyWrite(ok=False, error="the baseline template could not be read")
    path = os.path.join(project_root, COPY_BASENAME)
    template_sha = content_sha(template_text)
    facts = read_copy(path)
    state = classify_copy(facts, template_sha)

    if state == COPY_CURRENT:
        return CopyWrite(ok=True, state_before=state)
    if state not in _WRITABLE:
        return CopyWrite(ok=False, state_before=state,
                         error="%s is %s - not overwritten" % (COPY_BASENAME, state))
    if expect_recorded_sha is not None and facts.recorded_sha != expect_recorded_sha:
        return CopyWrite(ok=False, state_before=state,
                         error="%s changed since the plan" % COPY_BASENAME)

    ok, message = _atomic_write(path, render_copy(template_text), COPY_BASENAME)
    if not ok:
        return CopyWrite(ok=False, state_before=state, error=message)
    after = classify_copy(read_copy(path), template_sha)
    if after != COPY_CURRENT:
        return CopyWrite(ok=False, changed=True, state_before=state,
                         error="%s reads back as %s after writing"
                               % (COPY_BASENAME, after))
    return CopyWrite(ok=True, changed=True, state_before=state)


def read_template(baseline_path: str) -> str:
    """The template's text with its own line endings, or "" if unreadable."""
    try:
        with open(baseline_path, encoding="utf-8-sig", newline="") as handle:
            return handle.read()
    except (OSError, UnicodeDecodeError):
        return ""
