"""managed_copy — a file the Manager renders into a project and can judge later.

This is the one safety implementation behind every Manager-written instruction
copy: `project-baseline.md`, and each lesson under `docs/gotchas/`. It began as
`baseline_copy` and was made generic when a second kind of copy arrived, because
the alternative -- a `*_gotcha_*` twin of every function -- is two copies of the
same safety rules that drift.

## Identity is content, and the header records a claim about a SOURCE

Line one is a provenance header naming the source the copy was rendered from and
the sha256 of that source's body:

    <!-- tokensave-manager:copy gotchas/verifying-a-gui.md sha256=<hex> - note -->

The source is part of the identity, not decoration. Two lessons may have
identical bodies, and a hash alone could not say that `docs/gotchas/a.md` is a
copy of `a.md` rather than of `b.md`. A header whose source is not the one the
caller expects is `COPY_INVALID`: a damaged or mis-copied Manager file, never
overwritten.

Three hashes, one definition (`lf` then sha256 of UTF-8):

    body_sha      the copy's text after line one
    recorded_sha  the hex written in the header
    source_sha    the source as it is now

`recorded != body` means someone edited the copy; `recorded != source` means the
source moved on. Line endings are normalised first, so a CRLF checkout of an LF
render is still current.

**The header grammar is strict.** A file whose first line merely mentions the
marker is not Manager-owned, and a header that starts like ours but does not
parse is `COPY_INVALID` rather than `COPY_UNMANAGED`: a damaged Manager file must
not be indistinguishable from a person's own file, and neither is ever
overwritten.

**States are per artifact.** Nothing here aggregates; a caller that wants "three
outdated, one edited" counts them, and the facts stay per file.
"""

from __future__ import annotations

import hashlib
import os
import re
from dataclasses import dataclass

from helpers.io_utils import _atomic_write

_HEADER_PREFIX = "<!-- tokensave-manager:copy"
#: Source ids are relative POSIX-style names: no spaces, so the token after
#: `copy` is unambiguous.
_HEADER_RE = re.compile(
    r"^<!-- tokensave-manager:copy (\S+) "
    r"sha256=([0-9a-f]{64})(?: [^\r\n]*)? -->$")
_HEADER_NOTE = "- generated by TokenSave Manager; edit the template there, not this file"

COPY_ABSENT = "absent"
COPY_CURRENT = "current"
COPY_OUTDATED = "outdated"
COPY_EDITED = "edited"
COPY_INVALID = "invalid"
COPY_UNMANAGED = "unmanaged"
COPY_UNREADABLE = "unreadable"

#: States a write may replace. Everything else belongs to a person, or is a
#: file we cannot read and so cannot judge.
WRITABLE = (COPY_ABSENT, COPY_OUTDATED)

HEADER_OK = "ok"
HEADER_INVALID = "invalid"
HEADER_ABSENT = "absent"


def lf(text: str) -> str:
    """LF-normalised. The one normalisation every hash here goes through."""
    return (text or "").replace("\r\n", "\n").replace("\r", "\n")


def content_sha(text: str) -> str:
    return hashlib.sha256(lf(text).encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class ManagedCopySpec:
    """One artifact the Manager delivers: where, from what, and its text."""

    destination_rel: str
    source_id: str
    source_text: str


@dataclass(frozen=True)
class CopyFacts:
    """What one file says about itself. Knows nothing about the source."""

    exists: bool = False
    readable: bool = False
    header: str = HEADER_ABSENT
    recorded_sha: str = ""
    body_sha: str = ""
    text: str = ""
    #: The source the header names; "" when there is no parseable header.
    source_id: str = ""


def _split_first_line(text: str) -> "tuple[str, str]":
    """(line one without its terminator, everything after the terminator)."""
    for index, char in enumerate(text):
        if char == "\n":
            line = text[:index]
            if line.endswith("\r"):
                line = line[:-1]
            return line, text[index + 1:]
        if char == "\r" and not text.startswith("\n", index + 1):
            return text[:index], text[index + 1:]
    return text, ""


def parse_copy(text: str, source_id: "str | None" = None) -> CopyFacts:
    """Facts from a file's text. Pure.

    With *source_id*, a header that parses but names a DIFFERENT source is
    `HEADER_INVALID`: the file claims to be a copy of something else, so it is
    not ours to refresh. The check lives here, at parse time, so no caller can
    forget it when it classifies.
    """
    first, body = _split_first_line(text)
    match = _HEADER_RE.match(first)
    if match and source_id is not None and match.group(1) != source_id:
        return CopyFacts(exists=True, readable=True, header=HEADER_INVALID,
                         text=text)
    if match:
        return CopyFacts(exists=True, readable=True, header=HEADER_OK,
                         source_id=match.group(1), recorded_sha=match.group(2),
                         body_sha=content_sha(body), text=text)
    header = HEADER_INVALID if first.startswith(_HEADER_PREFIX) else HEADER_ABSENT
    return CopyFacts(exists=True, readable=True, header=header, text=text)


def read_copy(path: str, source_id: "str | None" = None) -> CopyFacts:
    """Facts about the file at *path*. Reads that one file and nothing else."""
    if not os.path.lexists(path):
        return CopyFacts()
    try:
        with open(path, encoding="utf-8", newline="") as handle:
            text = handle.read()
    except (OSError, UnicodeDecodeError):
        return CopyFacts(exists=True)
    return parse_copy(text, source_id)


def classify_copy(facts: CopyFacts, source_sha: str) -> str:
    """The copy's state against its source as it is now. Pure."""
    if not facts.exists:
        return COPY_ABSENT
    if not facts.readable:
        return COPY_UNREADABLE
    if facts.header == HEADER_ABSENT:
        return COPY_UNMANAGED
    if facts.header == HEADER_INVALID:
        return COPY_INVALID
    if facts.body_sha != facts.recorded_sha:
        return COPY_EDITED
    if facts.recorded_sha == source_sha:
        return COPY_CURRENT
    return COPY_OUTDATED


def _dominant_newline(text: str) -> str:
    crlf = text.count("\r\n")
    return "\r\n" if crlf > text.count("\n") - crlf else "\n"


def render_copy(source_text: str, source_id: str) -> str:
    """The exact bytes a copy of *source_text* holds. Deterministic."""
    header = "%s %s sha256=%s %s -->" % (
        _HEADER_PREFIX, source_id, content_sha(source_text), _HEADER_NOTE)
    return header + _dominant_newline(source_text) + source_text


@dataclass(frozen=True)
class CopyWrite:
    ok: bool
    changed: bool = False
    state_before: str = ""
    error: str = ""


def write_managed(project_root: str, spec: ManagedCopySpec,
                  expect_recorded_sha: "str | None" = None) -> CopyWrite:
    """Create or refresh one copy, then verify it.

    Compare-and-apply: the state is re-read here rather than trusted from a
    plan, and *expect_recorded_sha* (for a refresh) must still be what the file
    records. Only an absent or outdated copy is written; a copy that is already
    current is left byte-for-byte alone, which is what keeps a re-run from
    churning a committed file. Parent directories are created, but never
    outside *project_root*: `destination_rel` is a fixed name, not user input.
    """
    name = spec.destination_rel
    if not spec.source_text:
        return CopyWrite(ok=False,
                         error="the source for %s could not be read" % name)
    path = os.path.join(project_root, *name.split("/"))
    source_sha = content_sha(spec.source_text)
    facts = read_copy(path, spec.source_id)
    state = classify_copy(facts, source_sha)

    if state == COPY_CURRENT:
        return CopyWrite(ok=True, state_before=state)
    if state not in WRITABLE:
        return CopyWrite(ok=False, state_before=state,
                         error="%s is %s - not overwritten" % (name, state))
    if expect_recorded_sha is not None and facts.recorded_sha != expect_recorded_sha:
        return CopyWrite(ok=False, state_before=state,
                         error="%s changed since the plan" % name)

    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
    except OSError as exc:
        return CopyWrite(ok=False, state_before=state,
                         error="could not create the folder for %s: %s" % (name, exc))
    ok, message = _atomic_write(path, render_copy(spec.source_text, spec.source_id),
                                name)
    if not ok:
        return CopyWrite(ok=False, state_before=state, error=message)
    after = classify_copy(read_copy(path, spec.source_id), source_sha)
    if after != COPY_CURRENT:
        return CopyWrite(ok=False, changed=True, state_before=state,
                         error="%s reads back as %s after writing" % (name, after))
    return CopyWrite(ok=True, changed=True, state_before=state)


def read_source(path: str) -> str:
    """A source's text with its own line endings, or "" if unreadable."""
    try:
        with open(path, encoding="utf-8-sig", newline="") as handle:
            return handle.read()
    except (OSError, UnicodeDecodeError):
        return ""
