"""The post-read advisory hook: render it, install it, know whether it is there.

WHAT THIS IS. A ``PostToolUse`` hook on ``Read``. After an eligible whole-file
read in a project carrying tokensave metadata, the next model turn receives one
line saying ``tokensave_read`` can serve indexed content for that file. It is a
**post-read advisory, not an interception**: the model had already chosen its
tool before any hook ran, so the target is the *next* decision.

WHY IT EXISTS. Measured 2026-09-11 across the 8 transcripts touched since the
baseline's tokensave rule was strengthened: 319 ``Read`` against 21
``tokensave_read``, and all 21 of those in this repository. Fortuna Lab called
``tokensave_context`` 13 times, ``tokensave_status`` 6 and ``tokensave_search``
2 -- and ``tokensave_read`` zero times. The graph was in active use; only the
body read was unrouted. The difference is enforcement: tokensave's own
``PreToolUse`` hook matches ``Agent|Grep|Bash|Glob`` and has no file-body
branch, so the half of the rule that is enforced is the half that lands.

THREE RULES THIS MODULE KEEPS, each with its reason.

1. **The emitted object never carries a permission key.** Not ``deny``, and not
   ``allow`` either: ``allow`` skips the permission prompt, so a hook that "only
   ever allows" silently auto-approves every read it sees. Advisory means the
   output is ``additionalContext`` and nothing else. ``test_read_nudge`` asserts
   this across the whole input space it can reach, because it is the invariant
   keeping this feature from becoming a permissions change nobody asked for.

2. **``.tokensave/`` presence is a proxy, and the naming says so.** It
   establishes ``project_with_tokensave_metadata``, never ``is_indexed`` --
   freshness, ignore rules, parser coverage and exclusions all sit between the
   two facts. So the advisory says tokensave *can serve indexed content for* the
   file, which is what was checked, rather than promising the file comes back.
   This is the Roadmap-11 mistake -- a file-content verdict rendered as
   effective scope -- refusing to happen again somewhere new.

3. **Path identity is lexical, deliberately.** It matches
   ``instructions_posture.canonical``, so a path reached through a junction
   reads the same way here and in the Manager. Resolving links in the hook while
   the Manager does not would produce "Manager says indexed, nudge says not"
   with nothing to point at.

ONE SOURCE OF TRUTH FOR THE PREDICATE. ``HOOK_SCRIPT`` is a standalone script
AND an importable module: its predicate sits at module level and ``main()`` runs
only under ``__main__``. ``predicate_module()`` imports the rendered text, so
the adherence measurement in ``scripts/measure_tokensave_adherence.py`` runs the
*identical* predicate rather than a second implementation of it. A denominator
computed by a near-copy is the number most worth getting wrong quietly.

It is a string constant rather than a file read from disk for the same reason
``scaffold._AUTO_COMMIT_HELPER`` is: the Manager ships as a Nuitka build, where
``inspect.getsource`` and reading a sibling ``.py`` both fail.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import shutil
import sys
import tempfile
import time

from helpers.mcp_paths import _write_json_atomic

# ── Identity ──────────────────────────────────────────────────────────────
#: Bumping this is a deliberate migration: `installed_state` reports STALE and
#: `install` replaces exactly one owned entry. Tested, not merely intended.
HOOK_VERSION = 1
HOOK_MARKER = "tokensave-read-nudge"
HOOK_EVENT = "PostToolUse"
HOOK_MATCHER = "Read"
SCRIPT_BASENAME = "tokensave_read_nudge.py"

# ── Install states ────────────────────────────────────────────────────────
CURRENT = "current"
STALE = "stale"
DUPLICATE = "duplicate"
ABSENT = "absent"
UNKNOWN = "unknown"

#: Which half is wrong, so the diagnostic can say so. An entry that is perfect
#: beside a script somebody replaced by hand is not "the nudge is stale", and
#: telling the user it is sends them to the wrong repair.
HALF_ENTRY = "settings entry"
HALF_SCRIPT = "hook script"


_HOOK_HEADER = "# %s v%d\n" % (HOOK_MARKER, HOOK_VERSION)

_HOOK_BODY = '''"""Post-read advisory: one line, to the model, after a whole-file Read.

Generated by TokenSave Manager (helpers/read_nudge.py). Edit there, not here --
the Manager compares this file against its rendered form and reports a hand edit
as a hook script it no longer recognises.

Importable on purpose: the predicate is at module level and `main()` runs only
under `__main__`, so the Manager's adherence measurement imports and runs this
same code instead of reimplementing it.
"""

import json
import os
import sys

# `hashlib` and `tempfile` are imported lazily, inside the two functions that
# need them. Measured on this machine: a bare interpreter starts in 30.8 ms,
# `json`+`os`+`sys` costs 43.9, `hashlib` adds 6.5 and `tempfile` a further
# 14.3 -- and only an ELIGIBLE read ever reaches the state directory. Deferring
# them takes the common path (every sliced read, every image, every file
# outside an indexed project) from ~62 ms to ~44 ms, and that path runs far
# more often than the nudge does.

#: Serialised-response floor. Chosen from a measurement, not a feeling: over
#: 692 allowlisted whole-file reads (two weeks, 2026-09-11) the distribution was
#: p25 2,458 B, p50 6,453 B, p90 20,783 B. 2,048 B sits just under p25 and
#: excludes 20.2% of them -- roughly 500 tokens, below which the reminder costs
#: the same order as what it could save.
MIN_RESPONSE_BYTES = 2048
MAX_MARKERS = 500
MAX_ANCESTORS = 24
ENV_DISABLE = "TOKENSAVE_DISABLE_READ_NUDGE"
STATE_ROOT = "tokensave-read-nudge"
CAPPED_SENTINEL = ".capped"

ADVICE = ("This file is in a project with a tokensave index; tokensave_read "
          '(mode "lines" / "map") can serve indexed content for it.')

# Verdicts. Everything that is not ELIGIBLE is a reason rather than a bare
# False, so the measurement can report WHERE the denominator went instead of
# only how big it ended up.
NOT_READ = "not_read"
NO_PATH = "no_path"
SLICED = "sliced"
EXCLUDED_EXTENSION = "excluded_extension"
SMALL = "small"
NO_METADATA_PROJECT = "no_metadata_project"
ELIGIBLE = "eligible"
DISABLED = "disabled"
ALREADY_NUDGED = "already_nudged"

#: An allowlist, not a "looks like text" test: there is no budget to read a file
#: in order to decide whether to comment on reading it. Drawn from a measurement
#: of what actually gets read whole (2026-09-11, 1,382 reads over two weeks)
#: plus their obvious neighbours.
NUDGE_EXTENSIONS = frozenset({
    ".py", ".pyi", ".pyw",
    ".rs", ".go", ".rb", ".php", ".lua", ".swift", ".kt", ".java", ".cs",
    ".c", ".h", ".cpp", ".hpp", ".cc", ".hh",
    ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
    ".sh", ".ps1", ".bat", ".cmd", ".sql",
    ".md", ".rst", ".txt",
    ".json", ".jsonl", ".toml", ".yaml", ".yml", ".ini", ".cfg", ".properties",
    ".xml", ".html", ".css", ".scss", ".csv",
})

#: Excluded on purpose, each with its reason, so nobody later adds one back
#: because "it is text really":
#:   .ipynb -- Read renders notebooks as cells WITH OUTPUTS and tokensave_read
#:             does not, so a nudge here advertises a substitution that is not
#:             one.
#:   images and .pdf -- Read returns these as images/documents. Measured: 543 of
#:             1,382 whole-file reads, and the largest by payload (one .png
#:             serialised to 682 KB), so letting them reach the size gate would
#:             make base64 the loudest signal in the feature.
EXCLUDED_SPECIAL = frozenset({
    ".ipynb",
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".svg", ".pdf",
})


def response_bytes(tool_response):
    """Serialised UTF-8 bytes of what the hook was handed.

    NOT the file's size on disk: line numbering and truncation make those
    different numbers, and `tool_response` arrives as a dict (measured live on
    2026-09-11, not assumed). This is the payload, which is the thing that was
    expensive.
    """
    if tool_response is None:
        return 0
    try:
        text = (tool_response if isinstance(tool_response, str)
                else json.dumps(tool_response))
    except (TypeError, ValueError):
        return 0
    return len(text.encode("utf-8", "replace"))


def classify_read(tool_name, tool_input, size_bytes, in_metadata_project):
    """Pure. The whole eligibility decision, with no filesystem and no state.

    Shared verbatim with the adherence measurement -- see the module docstring
    of helpers/read_nudge.py for why that matters.
    """
    if tool_name != "Read":
        return NOT_READ
    tool_input = tool_input or {}
    # `file_path` in 320 of 320 real Read records. `path` is read too because a
    # documentation summary claimed that name, and being wrong here would mean a
    # hook that resolves nothing and silently never fires.
    path = tool_input.get("file_path") or tool_input.get("path") or ""
    if not path:
        return NO_PATH
    if "offset" in tool_input or "limit" in tool_input:
        return SLICED
    ext = os.path.splitext(path)[1].lower()
    if ext in EXCLUDED_SPECIAL or ext not in NUDGE_EXTENSIONS:
        return EXCLUDED_EXTENSION
    if size_bytes < MIN_RESPONSE_BYTES:
        return SMALL
    if not in_metadata_project:
        return NO_METADATA_PROJECT
    return ELIGIBLE


def project_with_tokensave_metadata(file_path, cwd, max_ancestors=MAX_ANCESTORS):
    """Does a `.tokensave/` sit at or above this file, within this session?

    Bounded at `cwd`, because an unbounded walk lets one stray
    `D:/projects/.tokensave` mark every unrelated child project as served. A
    file outside `cwd` entirely is not this session's project, so it stops at
    the ancestor bound rather than climbing to the drive root.

    Lexical throughout -- see rule 3 in helpers/read_nudge.py.
    """
    try:
        current = os.path.dirname(os.path.normcase(os.path.abspath(file_path)))
    except (OSError, ValueError):
        return False

    stop = ""
    if cwd:
        try:
            stop = os.path.normcase(os.path.abspath(cwd))
        except (OSError, ValueError):
            stop = ""
        # A file outside the session's directory is not this session's project.
        # Tools can be handed an absolute path anywhere on the machine, and
        # walking up from one would let an unrelated repository's metadata
        # answer for it.
        if stop and current != stop and not current.startswith(stop + os.sep):
            return False

    for _ in range(max_ancestors):
        try:
            if os.path.isdir(os.path.join(current, ".tokensave")):
                return True
        except OSError:
            return False
        # `cwd` itself is tested, and nothing above it is: one stray
        # `D:/projects/.tokensave` must not mark every repository beneath it.
        if stop and current == stop:
            return False
        parent = os.path.dirname(current)
        if parent == current:
            return False
        current = parent
    return False


def _temp_root():
    """The seam the tests patch, and the lazy import in one place."""
    import tempfile

    return tempfile.gettempdir()


def _digest(text):
    import hashlib

    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _state_dir(session_id):
    return os.path.join(_temp_root(), STATE_ROOT,
                        _digest(session_id or "no-session")[:16])


def claim_first_sighting(session_id, file_path):
    """True exactly once per (session, file). Atomic, no read-modify-write.

    `O_CREAT | O_EXCL` IS the test and the claim in one syscall, so two hooks
    racing on the same file cannot both see "not yet nudged" -- which a shared
    JSON state file could not prevent, and which parallel PostToolUse execution
    makes possible even though it measured 0 of 320 reads on this machine.

    Bounded: once the directory reaches MAX_MARKERS a sentinel is dropped, and
    from then on the hot path is a single `exists` rather than a directory walk.
    Markers are empty files, so bounding the count bounds the bytes.

    It stores no paths, because it does not need them -- that is a "keep no more
    than the job requires" rule, not a claim of anonymisation.
    """
    directory = _state_dir(session_id)
    sentinel = os.path.join(directory, CAPPED_SENTINEL)
    try:
        if os.path.exists(sentinel):
            return False
        os.makedirs(directory, exist_ok=True)
        digest = _digest(os.path.normcase(os.path.abspath(file_path)))
        try:
            handle = os.open(os.path.join(directory, digest[:32]),
                             os.O_CREAT | os.O_EXCL | os.O_WRONLY)
        except FileExistsError:
            return False
        os.close(handle)
        count = 0
        with os.scandir(directory) as entries:
            for _entry in entries:
                count += 1
                if count > MAX_MARKERS:
                    break
        if count > MAX_MARKERS:
            os.close(os.open(sentinel, os.O_CREAT | os.O_WRONLY))
        return True
    except OSError:
        return False


def decide(payload):
    """`(verdict, advice_or_empty)`. No permission key is produced anywhere."""
    if os.environ.get(ENV_DISABLE):
        return DISABLED, ""
    tool_input = payload.get("tool_input") or {}
    path = tool_input.get("file_path") or tool_input.get("path") or ""
    verdict = classify_read(
        payload.get("tool_name"),
        tool_input,
        response_bytes(payload.get("tool_response")),
        project_with_tokensave_metadata(path, payload.get("cwd") or ""),
    )
    if verdict != ELIGIBLE:
        return verdict, ""
    if not claim_first_sighting(payload.get("session_id") or "", path):
        return ALREADY_NUDGED, ""
    return ELIGIBLE, ADVICE


def main():
    """Fail open, always. A broken advisory must never cost anybody a read."""
    try:
        payload = json.loads(sys.stdin.read() or "{}")
        if not isinstance(payload, dict):
            return
        _verdict, advice = decide(payload)
        if not advice:
            return
        sys.stdout.write(json.dumps({"hookSpecificOutput": {
            "hookEventName": "PostToolUse",
            "additionalContext": advice,
        }}))
    except Exception:
        return


if __name__ == "__main__":
    main()
'''

HOOK_SCRIPT = _HOOK_HEADER + _HOOK_BODY


def render_hook_script() -> str:
    """The artifact's exact text. Identity is computed from this, never guessed."""
    return HOOK_SCRIPT


def script_fingerprint(text: str) -> str:
    """Content identity, newline-insensitive.

    A checkout or an editor may rewrite line endings without changing a single
    instruction, and calling that a stale hook would send the user to a repair
    that changes nothing.
    """
    normalised = (text or "").replace("\r\n", "\n").replace("\r", "\n")
    return hashlib.sha256(normalised.encode("utf-8")).hexdigest()


def default_script_path() -> str:
    """`~/.claude/hooks/` -- deliberately NOT the Manager's install directory.

    Rule D1f: an absolute pointer into the install dir is one more thing a
    relocation breaks, and `template_dir` is meant to be the only relocatable
    key. The Manager owns this file's content; the home directory owns where it
    lives.
    """
    return os.path.join(os.path.expanduser("~"), ".claude", "hooks",
                        SCRIPT_BASENAME)


def default_settings_path() -> str:
    return os.path.join(os.path.expanduser("~"), ".claude", "settings.json")


def predicate_module():
    """Import the rendered script and hand back its module.

    This is what makes "the measurement uses the hook's predicate" true rather
    than aspirational: there is no second copy for it to drift from.
    """
    directory = os.path.join(tempfile.gettempdir(), "tokensave-read-nudge-src")
    os.makedirs(directory, exist_ok=True)
    text = render_hook_script()
    path = os.path.join(directory, "nudge_%s.py" % script_fingerprint(text)[:16])
    if not os.path.isfile(path):
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(text)
    spec = importlib.util.spec_from_file_location("tokensave_read_nudge", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def resolve_interpreter(python_exe: str = "") -> "tuple[str, str]":
    """`(interpreter, error)`. A console python, never `pythonw`, never bare.

    `pythonw.exe` has no stdout to write the advisory to, and a bare `python` is
    not reliably resolvable from a hook's environment. Returning an error rather
    than a guess is the point: a hook that cannot run is worse than no hook,
    because it looks installed.
    """
    candidates = []
    if python_exe:
        base = os.path.basename(python_exe)
        if base.lower().startswith("pythonw"):
            candidates.append(os.path.join(
                os.path.dirname(python_exe),
                base[:6] + base[7:]))  # pythonw.exe -> python.exe, case kept
        else:
            candidates.append(python_exe)
    if (sys.executable
            and not os.path.basename(sys.executable).lower().startswith("pythonw")):
        candidates.append(sys.executable)
    for name in ("python.exe", "python3", "python"):
        found = shutil.which(name)
        if found:
            candidates.append(found)
    for candidate in candidates:
        if candidate and os.path.isfile(candidate):
            return candidate, ""
    return "", ("No console Python interpreter could be resolved, so the hook "
                "was not installed. A hook that cannot run looks installed and "
                "advises nothing.")


def hook_entry(interpreter: str, script_path: str) -> dict:
    """The one owned settings entry.

    `command` + `args` array, the shape tokensave's own entries use and the one
    the hook-quoting bug was fixed to -- so no shell quoting is involved at all.
    """
    return {
        "matcher": HOOK_MATCHER,
        "hooks": [{"type": "command", "command": interpreter,
                   "args": [script_path]}],
    }


def is_owned_entry(entry: dict, script_path: str = "") -> bool:
    """Ours, structurally -- never "a Read hook that looks a bit like ours".

    A hand-written hook of the user's that happens to match `Read`, or that
    happens to contain our marker string, is not ours and is never repaired or
    replaced. D1b's "unknown is never false", applied to ownership.
    """
    if not isinstance(entry, dict) or entry.get("matcher") != HOOK_MATCHER:
        return False
    target = os.path.normcase(os.path.abspath(script_path or default_script_path()))
    for handler in entry.get("hooks") or []:
        if not isinstance(handler, dict) or handler.get("type") != "command":
            continue
        for arg in handler.get("args") or []:
            try:
                if os.path.normcase(os.path.abspath(str(arg))) == target:
                    return True
            except (OSError, ValueError):
                continue
    return False


def _read_settings(settings_path: str) -> "tuple[dict, str]":
    """`(settings, unknown_reason)`. Absent is a fact; unreadable is not.

    An absent settings file is an empty one for our purposes -- there is simply
    no owned entry in it. Unreadable and malformed are different, and both are
    UNKNOWN with distinct reasons, because a repair written on top of a file we
    could not parse is exactly the agent-control accident this protocol exists
    to prevent.
    """
    if not os.path.exists(settings_path):
        return {}, ""
    try:
        with open(settings_path, encoding="utf-8-sig") as handle:
            raw = handle.read()
    except OSError as exc:
        return {}, "settings unreadable (%s)" % exc.__class__.__name__
    try:
        data = json.loads(raw or "{}")
    except ValueError:
        return {}, "settings JSON malformed"
    if not isinstance(data, dict):
        return {}, "settings JSON is not an object"
    return data, ""


def owned_entries(settings: dict, script_path: str = "") -> list:
    """Indices of our entries within `hooks.PostToolUse`, in order."""
    entries = ((settings.get("hooks") or {}).get(HOOK_EVENT) or [])
    if not isinstance(entries, list):
        return []
    return [index for index, entry in enumerate(entries)
            if is_owned_entry(entry, script_path)]


def installed_state(settings_path: str = "",
                    script_path: str = "") -> "tuple[str, str]":
    """`(state, detail)` over BOTH identities -- the entry and the script.

    They are checked independently and the detail names which half is wrong.
    "Read nudge stale" when the entry is perfect and somebody replaced the
    script by hand is a misleading prompt rather than a diagnosis.
    """
    settings_path = settings_path or default_settings_path()
    script_path = script_path or default_script_path()

    settings, unknown = _read_settings(settings_path)
    if unknown:
        return UNKNOWN, unknown

    indices = owned_entries(settings, script_path)
    if not indices:
        return ABSENT, "no owned %s entry in %s" % (HOOK_EVENT, settings_path)
    if len(indices) > 1:
        return DUPLICATE, ("%d owned %s entries; exactly one is expected"
                           % (len(indices), HOOK_EVENT))

    if not os.path.exists(script_path):
        return STALE, "%s present, but %s is missing" % (HALF_ENTRY, script_path)
    try:
        with open(script_path, encoding="utf-8") as handle:
            on_disk = handle.read()
    except OSError as exc:
        return UNKNOWN, "script unreadable (%s)" % exc.__class__.__name__

    if script_fingerprint(on_disk) != script_fingerprint(render_hook_script()):
        return STALE, ("%s is current; the %s does not match the version this "
                       "Manager generates" % (HALF_ENTRY, HALF_SCRIPT))
    return CURRENT, ""


def install(python_exe: str = "", settings_path: str = "",
            script_path: str = "") -> "tuple[bool, str, list]":
    """Write the script and register exactly one owned entry. `(ok, error, actions)`.

    Refuses rather than guesses, in two places that matter:

    * **No interpreter, no install.** A hook whose command cannot run looks
      installed and advises nothing, which is strictly worse than its absence.
    * **Unreadable or malformed settings, no install.** A lenient parser could
      often salvage enough of a broken `settings.json` to append to, and doing
      so would rewrite an agent-control file we admit we did not understand.
      The warning is the better outcome.

    Everything not ours survives. The file legitimately holds other event
    groups, other matchers, several handlers per entry and hand-written
    additions; this loads, edits one entry, and writes the whole object back
    atomically.
    """
    settings_path = settings_path or default_settings_path()
    script_path = script_path or default_script_path()

    interpreter, error = resolve_interpreter(python_exe)
    if error:
        return False, error, []

    settings, unknown = _read_settings(settings_path)
    if unknown:
        return False, ("Refusing to write: %s. This is an agent-control file, "
                       "and a repair written over one that could not be parsed "
                       "is worse than the warning it would silence." % unknown), []

    hooks = settings.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        return False, "Refusing to write: `hooks` is not an object.", []
    entries = hooks.setdefault(HOOK_EVENT, [])
    if not isinstance(entries, list):
        return False, "Refusing to write: `hooks.%s` is not a list." % HOOK_EVENT, []

    actions = []
    try:
        os.makedirs(os.path.dirname(script_path), exist_ok=True)
        with open(script_path, "w", encoding="utf-8") as handle:
            handle.write(render_hook_script())
    except OSError as exc:
        return False, "Could not write %s: %s" % (script_path, exc), []
    actions.append("Wrote %s (v%d)" % (script_path, HOOK_VERSION))

    indices = owned_entries(settings, script_path)
    entry = hook_entry(interpreter, script_path)
    if indices:
        entries[indices[0]] = entry
        for index in reversed(indices[1:]):
            del entries[index]
            actions.append("Removed a duplicate owned %s entry" % HOOK_EVENT)
        actions.append("Updated the owned %s entry" % HOOK_EVENT)
    else:
        entries.append(entry)
        actions.append("Added the owned %s entry (matcher %r)"
                       % (HOOK_EVENT, HOOK_MATCHER))

    # The backup happens only now -- after every refusal above, so a validation
    # failure leaves no litter behind it.
    if os.path.exists(settings_path):
        backup = "%s.backup.%d" % (settings_path, int(time.time() * 1000))
        try:
            shutil.copy2(settings_path, backup)
        except OSError as exc:
            return False, "Could not back up %s: %s" % (settings_path, exc), actions
        actions.append("Backed up to %s" % backup)

    ok, write_error = _write_json_atomic(settings_path, settings)
    if not ok:
        return False, write_error, actions
    actions.append("Wrote %s" % settings_path)
    return True, "", actions
