"""The post-read advisory hook: render it, install it, know whether it is there.

WHAT THIS IS. A ``PostToolUse`` hook on ``Read``. After an eligible whole-file
read in a project carrying tokensave metadata, the next model turn receives one
line saying ``tokensave_read`` can serve indexed content for that file. It is a
**post-read advisory, not an interception**: the model had already chosen its
tool before any hook ran, so the target is the *next* decision.

WHY IT EXISTS. Measured 2026-09-11 across the 8 transcripts touched since the
baseline's tokensave rule was strengthened: 319 ``Read`` against 21
``tokensave_read``, and all 21 of those in this repository. Fortuna Lab called
``tokensave_context`` 13 times, ``tokensave_status`` 6 and ``tokensave_search``
2 -- and ``tokensave_read`` zero times. The graph was in active use; only the
body read was unrouted. The difference is enforcement: tokensave's own
``PreToolUse`` hook matches ``Agent|Grep|Bash|Glob`` and has no file-body
branch, so the half of the rule that is enforced is the half that lands.

THREE RULES THIS MODULE KEEPS, each with its reason.

1. **The emitted object never carries a permission key.** Not ``deny``, and not
   ``allow`` either: ``allow`` skips the permission prompt, so a hook that "only
   ever allows" silently auto-approves every read it sees. Advisory means the
   output is ``additionalContext`` and nothing else. ``test_read_nudge`` asserts
   this across the whole input space it can reach, because it is the invariant
   keeping this feature from becoming a permissions change nobody asked for.

2. **``.tokensave/`` presence is a proxy, and the naming says so.** It
   establishes ``project_with_tokensave_metadata``, never ``is_indexed`` --
   freshness, ignore rules, parser coverage and exclusions all sit between the
   two facts. So the advisory says tokensave *can serve indexed content for* the
   file, which is what was checked, rather than promising the file comes back.
   This is the Roadmap-11 mistake -- a file-content verdict rendered as
   effective scope -- refusing to happen again somewhere new.

3. **Path identity is lexical, deliberately.** It matches
   ``instructions_posture.canonical``, so a path reached through a junction
   reads the same way here and in the Manager. Resolving links in the hook while
   the Manager does not would produce "Manager says indexed, nudge says not"
   with nothing to point at.

ONE SOURCE OF TRUTH FOR THE PREDICATE. ``HOOK_SCRIPT`` is a standalone script
AND an importable module: its predicate sits at module level and ``main()`` runs
only under ``__main__``. ``predicate_module()`` imports the rendered text, so
the adherence measurement in ``scripts/measure_tokensave_adherence.py`` runs the
*identical* predicate rather than a second implementation of it. A denominator
computed by a near-copy is the number most worth getting wrong quietly.

It is a string constant rather than a file read from disk for the same reason
``scaffold._AUTO_COMMIT_HELPER`` is: the Manager ships as a Nuitka build, where
``inspect.getsource`` and reading a sibling ``.py`` both fail.
"""

from __future__ import annotations

import importlib.util
import os
import tempfile

from helpers import claude_hooks

# ── Identity ──────────────────────────────────────────────────────────────
#: Bumping this is a deliberate migration: `installed_state` reports STALE and
#: `install` replaces exactly one owned entry. Tested, not merely intended.
HOOK_VERSION = 1
HOOK_MARKER = "tokensave-read-nudge"
HOOK_EVENT = "PostToolUse"
HOOK_MATCHER = "Read"
SCRIPT_BASENAME = "tokensave_read_nudge.py"

# ── Install states: the shared vocabulary, re-exported ────────────────────
CURRENT = claude_hooks.CURRENT
STALE = claude_hooks.STALE
DUPLICATE = claude_hooks.DUPLICATE
ABSENT = claude_hooks.ABSENT
UNKNOWN = claude_hooks.UNKNOWN
HALF_ENTRY = claude_hooks.HALF_ENTRY
HALF_SCRIPT = claude_hooks.HALF_SCRIPT


_HOOK_HEADER = "# %s v%d\n" % (HOOK_MARKER, HOOK_VERSION)

_HOOK_BODY = '''"""Post-read advisory: one line, to the model, after a whole-file Read.

Generated by TokenSave Manager (helpers/read_nudge.py). Edit there, not here --
the Manager compares this file against its rendered form and reports a hand edit
as a hook script it no longer recognises.

Importable on purpose: the predicate is at module level and `main()` runs only
under `__main__`, so the Manager's adherence measurement imports and runs this
same code instead of reimplementing it.
"""

import json
import os
import sys

# `hashlib` and `tempfile` are imported lazily, inside the two functions that
# need them. Measured on this machine: a bare interpreter starts in 30.8 ms,
# `json`+`os`+`sys` costs 43.9, `hashlib` adds 6.5 and `tempfile` a further
# 14.3 -- and only an ELIGIBLE read ever reaches the state directory. Deferring
# them takes the common path (every sliced read, every image, every file
# outside an indexed project) from ~62 ms to ~44 ms, and that path runs far
# more often than the nudge does.

#: Serialised-response floor. Chosen from a measurement, not a feeling: over
#: 692 allowlisted whole-file reads (two weeks, 2026-09-11) the distribution was
#: p25 2,458 B, p50 6,453 B, p90 20,783 B. 2,048 B sits just under p25 and
#: excludes 20.2% of them -- roughly 500 tokens, below which the reminder costs
#: the same order as what it could save.
MIN_RESPONSE_BYTES = 2048
MAX_MARKERS = 500
MAX_ANCESTORS = 24
ENV_DISABLE = "TOKENSAVE_DISABLE_READ_NUDGE"
STATE_ROOT = "tokensave-read-nudge"
CAPPED_SENTINEL = ".capped"

ADVICE = ("This file is in a project with a tokensave index; tokensave_read "
          '(mode "lines" / "map") can serve indexed content for it.')

# Verdicts. Everything that is not ELIGIBLE is a reason rather than a bare
# False, so the measurement can report WHERE the denominator went instead of
# only how big it ended up.
NOT_READ = "not_read"
NO_PATH = "no_path"
SLICED = "sliced"
EXCLUDED_EXTENSION = "excluded_extension"
SMALL = "small"
NO_METADATA_PROJECT = "no_metadata_project"
ELIGIBLE = "eligible"
DISABLED = "disabled"
ALREADY_NUDGED = "already_nudged"

#: An allowlist, not a "looks like text" test: there is no budget to read a file
#: in order to decide whether to comment on reading it. Drawn from a measurement
#: of what actually gets read whole (2026-09-11, 1,382 reads over two weeks)
#: plus their obvious neighbours.
NUDGE_EXTENSIONS = frozenset({
    ".py", ".pyi", ".pyw",
    ".rs", ".go", ".rb", ".php", ".lua", ".swift", ".kt", ".java", ".cs",
    ".c", ".h", ".cpp", ".hpp", ".cc", ".hh",
    ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
    ".sh", ".ps1", ".bat", ".cmd", ".sql",
    ".md", ".rst", ".txt",
    ".json", ".jsonl", ".toml", ".yaml", ".yml", ".ini", ".cfg", ".properties",
    ".xml", ".html", ".css", ".scss", ".csv",
})

#: Excluded on purpose, each with its reason, so nobody later adds one back
#: because "it is text really":
#:   .ipynb -- Read renders notebooks as cells WITH OUTPUTS and tokensave_read
#:             does not, so a nudge here advertises a substitution that is not
#:             one.
#:   images and .pdf -- Read returns these as images/documents. Measured: 543 of
#:             1,382 whole-file reads, and the largest by payload (one .png
#:             serialised to 682 KB), so letting them reach the size gate would
#:             make base64 the loudest signal in the feature.
EXCLUDED_SPECIAL = frozenset({
    ".ipynb",
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".svg", ".pdf",
})


def response_bytes(tool_response):
    """Serialised UTF-8 bytes of what the hook was handed.

    NOT the file's size on disk: line numbering and truncation make those
    different numbers, and `tool_response` arrives as a dict (measured live on
    2026-09-11, not assumed). This is the payload, which is the thing that was
    expensive.
    """
    if tool_response is None:
        return 0
    try:
        text = (tool_response if isinstance(tool_response, str)
                else json.dumps(tool_response))
    except (TypeError, ValueError):
        return 0
    return len(text.encode("utf-8", "replace"))


def classify_read(tool_name, tool_input, size_bytes, in_metadata_project):
    """Pure. The whole eligibility decision, with no filesystem and no state.

    Shared verbatim with the adherence measurement -- see the module docstring
    of helpers/read_nudge.py for why that matters.
    """
    if tool_name != "Read":
        return NOT_READ
    tool_input = tool_input or {}
    # `file_path` in 320 of 320 real Read records. `path` is read too because a
    # documentation summary claimed that name, and being wrong here would mean a
    # hook that resolves nothing and silently never fires.
    path = tool_input.get("file_path") or tool_input.get("path") or ""
    if not path:
        return NO_PATH
    if "offset" in tool_input or "limit" in tool_input:
        return SLICED
    ext = os.path.splitext(path)[1].lower()
    if ext in EXCLUDED_SPECIAL or ext not in NUDGE_EXTENSIONS:
        return EXCLUDED_EXTENSION
    if size_bytes < MIN_RESPONSE_BYTES:
        return SMALL
    if not in_metadata_project:
        return NO_METADATA_PROJECT
    return ELIGIBLE


def project_with_tokensave_metadata(file_path, cwd, max_ancestors=MAX_ANCESTORS):
    """Does a `.tokensave/` sit at or above this file, within this session?

    Bounded at `cwd`, because an unbounded walk lets one stray
    `D:/projects/.tokensave` mark every unrelated child project as served. A
    file outside `cwd` entirely is not this session's project, so it stops at
    the ancestor bound rather than climbing to the drive root.

    Lexical throughout -- see rule 3 in helpers/read_nudge.py.
    """
    try:
        current = os.path.dirname(os.path.normcase(os.path.abspath(file_path)))
    except (OSError, ValueError):
        return False

    stop = ""
    if cwd:
        try:
            stop = os.path.normcase(os.path.abspath(cwd))
        except (OSError, ValueError):
            stop = ""
        # A file outside the session's directory is not this session's project.
        # Tools can be handed an absolute path anywhere on the machine, and
        # walking up from one would let an unrelated repository's metadata
        # answer for it.
        if stop and current != stop and not current.startswith(stop + os.sep):
            return False

    for _ in range(max_ancestors):
        try:
            if os.path.isdir(os.path.join(current, ".tokensave")):
                return True
        except OSError:
            return False
        # `cwd` itself is tested, and nothing above it is: one stray
        # `D:/projects/.tokensave` must not mark every repository beneath it.
        if stop and current == stop:
            return False
        parent = os.path.dirname(current)
        if parent == current:
            return False
        current = parent
    return False


def _temp_root():
    """The seam the tests patch, and the lazy import in one place."""
    import tempfile

    return tempfile.gettempdir()


def _digest(text):
    import hashlib

    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _state_dir(session_id):
    return os.path.join(_temp_root(), STATE_ROOT,
                        _digest(session_id or "no-session")[:16])


def claim_first_sighting(session_id, file_path):
    """True exactly once per (session, file). Atomic, no read-modify-write.

    `O_CREAT | O_EXCL` IS the test and the claim in one syscall, so two hooks
    racing on the same file cannot both see "not yet nudged" -- which a shared
    JSON state file could not prevent, and which parallel PostToolUse execution
    makes possible even though it measured 0 of 320 reads on this machine.

    Bounded: once the directory reaches MAX_MARKERS a sentinel is dropped, and
    from then on the hot path is a single `exists` rather than a directory walk.
    Markers are empty files, so bounding the count bounds the bytes.

    It stores no paths, because it does not need them -- that is a "keep no more
    than the job requires" rule, not a claim of anonymisation.
    """
    directory = _state_dir(session_id)
    sentinel = os.path.join(directory, CAPPED_SENTINEL)
    try:
        if os.path.exists(sentinel):
            return False
        os.makedirs(directory, exist_ok=True)
        digest = _digest(os.path.normcase(os.path.abspath(file_path)))
        try:
            handle = os.open(os.path.join(directory, digest[:32]),
                             os.O_CREAT | os.O_EXCL | os.O_WRONLY)
        except FileExistsError:
            return False
        os.close(handle)
        count = 0
        with os.scandir(directory) as entries:
            for _entry in entries:
                count += 1
                if count > MAX_MARKERS:
                    break
        if count > MAX_MARKERS:
            os.close(os.open(sentinel, os.O_CREAT | os.O_WRONLY))
        return True
    except OSError:
        return False


def decide(payload):
    """`(verdict, advice_or_empty)`. No permission key is produced anywhere."""
    if os.environ.get(ENV_DISABLE):
        return DISABLED, ""
    tool_input = payload.get("tool_input") or {}
    path = tool_input.get("file_path") or tool_input.get("path") or ""
    verdict = classify_read(
        payload.get("tool_name"),
        tool_input,
        response_bytes(payload.get("tool_response")),
        project_with_tokensave_metadata(path, payload.get("cwd") or ""),
    )
    if verdict != ELIGIBLE:
        return verdict, ""
    if not claim_first_sighting(payload.get("session_id") or "", path):
        return ALREADY_NUDGED, ""
    return ELIGIBLE, ADVICE


def main():
    """Fail open, always. A broken advisory must never cost anybody a read."""
    try:
        payload = json.loads(sys.stdin.read() or "{}")
        if not isinstance(payload, dict):
            return
        _verdict, advice = decide(payload)
        if not advice:
            return
        sys.stdout.write(json.dumps({"hookSpecificOutput": {
            "hookEventName": "PostToolUse",
            "additionalContext": advice,
        }}))
    except Exception:
        return


if __name__ == "__main__":
    main()
'''

#: This hook, as a row. Everything generic — resolving an interpreter, owning
#: exactly one entry, backing up and rewriting settings, reporting state —
#: lives in `helpers/claude_hooks.py`, because the session note is the second
#: hook and the second is where a literal becomes a table.
SPEC = claude_hooks.HookSpec(
    marker=HOOK_MARKER,
    version=HOOK_VERSION,
    event=HOOK_EVENT,
    matcher=HOOK_MATCHER,
    basename=SCRIPT_BASENAME,
    body=_HOOK_BODY,
)

HOOK_SCRIPT = SPEC.script


def render_hook_script() -> str:
    """The artifact's exact text. Identity is computed from this, never guessed."""
    return SPEC.script


def script_fingerprint(text: str) -> str:
    return claude_hooks.script_fingerprint(text)


def default_script_path() -> str:
    return claude_hooks.default_script_path(SPEC)


def default_settings_path() -> str:
    return claude_hooks.default_settings_path()


def resolve_interpreter(python_exe: str = "") -> "tuple[str, str]":
    return claude_hooks.resolve_interpreter(python_exe)


def hook_entry(interpreter: str, script_path: str) -> dict:
    return claude_hooks.hook_entry(SPEC, interpreter, script_path)


def is_owned_entry(entry: dict, script_path: str = "") -> bool:
    return claude_hooks.is_owned_entry(
        SPEC, entry, script_path or default_script_path())


def owned_entries(settings: dict, script_path: str = "") -> list:
    return claude_hooks.owned_entries(
        SPEC, settings, script_path or default_script_path())


def installed_state(settings_path: str = "",
                    script_path: str = "") -> "tuple[str, str]":
    return claude_hooks.installed_state(SPEC, settings_path, script_path)


def install(python_exe: str = "", settings_path: str = "",
            script_path: str = "") -> "tuple[bool, str, list]":
    return claude_hooks.install(SPEC, python_exe, settings_path, script_path)


def uninstall(settings_path: str = "",
              script_path: str = "") -> "tuple[bool, str, list]":
    """Available for symmetry; the read nudge has no OFF toggle yet."""
    return claude_hooks.uninstall(SPEC, settings_path, script_path)


def predicate_module():
    """Import the rendered script and hand back its module.

    This is what makes "the measurement uses the hook's predicate" true rather
    than aspirational: there is no second copy for it to drift from.
    """
    directory = os.path.join(tempfile.gettempdir(), "tokensave-read-nudge-src")
    os.makedirs(directory, exist_ok=True)
    text = render_hook_script()
    path = os.path.join(directory, "nudge_%s.py" % script_fingerprint(text)[:16])
    if not os.path.isfile(path):
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(text)
    spec = importlib.util.spec_from_file_location("tokensave_read_nudge", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module
