"""What a Claude Code session was FOR, captured at the moment it ended.

A `Stop` hook writes `<project>/.claude/session-note.json` recording the user's
own prompts for that session. It exists because of a measured gap: Claude Code
writes better commit messages than Claude CLI, which beats Ollama — and since
Claude CLI is the same model family, the variable is **what each one knows**,
not model size. A session that wrote the code knows *why*; everything invoked
afterwards is handed a cold diff and must infer it.

The note closes that gap at the cheapest point. Measured across one day of this
repo's transcripts: the user's prompts are ~1,200 tokens, assistant prose
~20,200, and thinking blocks are **not persisted at all** (203 blocks, 0 chars).
Prompts are small, they are the intent in the user's own words, and summarising
supplied text is something a small local model does well — unlike inferring
intent from a diff, which is the hardest possible framing of the task.

WHAT IT CAPTURES, AND WHAT IT DELIBERATELY DOES NOT. `prompts[]` only. The Stop
payload also hands over `last_assistant_message` (measured 2026-09-12, it is a
real field), and capturing it would be free — but only prompts are
authoritative, nothing consumes a summary yet, and every captured byte is a byte
stored and later fed to a model. It can be added when the Phase C measurement
shows prose earns its place, and not before.

WHICH PROJECT A NOTE BELONGS TO is a rule, not an implementation detail: the git
root containing the payload's **declared `cwd`**, falling back to `cwd` itself,
and nothing is written when that is not a repository. Never inferred from shell
activity — measured on this very session, whose `cwd` was this repo while it ran
commands inside another project entirely, so activity would have filed the note
against the wrong one.

THE READ IS BOUNDED AT BOTH ENDS. Transcripts measured p50 0.9 MB, p90 14.2 MB,
p99 112 MB, max 134 MB. A forward stream of the worst case would add seconds to
every session end, so this reads a bounded head AND a bounded tail — the head
because a session's opening ask is usually its clearest statement of intent, the
tail because recent prompts describe the work being committed — and records
`truncated` when the middle was skipped. A partial capture that says so is
honest; one that silently looks complete is not.

It knows nothing about drafting. A guard test forbids importing PR-draft,
commit-message or grounding modules: Phase C consumes this, and the Ask tab or
doc drafter might later.
"""

from __future__ import annotations

import json
import os

from helpers import claude_hooks

HOOK_VERSION = 1
HOOK_MARKER = "tokensave-session-note"
SCRIPT_BASENAME = "tokensave_session_note.py"
NOTE_BASENAME = "session-note.json"

# Re-exported so callers speak one vocabulary for every owned hook.
CURRENT = claude_hooks.CURRENT
STALE = claude_hooks.STALE
DUPLICATE = claude_hooks.DUPLICATE
ABSENT = claude_hooks.ABSENT
UNKNOWN = claude_hooks.UNKNOWN


_HOOK_BODY = '''"""Record what this session was for, next to the repo it touched.

Generated by TokenSave Manager (helpers/session_note.py). Edit there, not here.
"""

import json
import os
import sys
import tempfile

NOTE_BASENAME = "session-note.json"
NOTE_VERSION = 1

#: Bounded at both ends rather than streamed whole: transcripts measured p99
#: 112 MB, and a Stop hook that reads all of one adds seconds to session end.
#: Head for the opening ask, tail for the recent work.
HEAD_BYTES = 2_000_000
TAIL_BYTES = 6_000_000
MAX_PROMPTS = 40
MAX_PROMPT_CHARS = 2_000
MAX_SESSIONS = 20
MAX_ANCESTORS = 24


def project_root(cwd):
    """The git root containing `cwd`, else "" — never guessed from activity.

    `.git` may be a directory OR a worktree pointer file, so this tests for
    existence rather than isdir: the project's `_is_local_git_repo` rule.
    """
    # Guarded BEFORE abspath: os.path.abspath("") returns the *hook process's*
    # working directory, so an empty cwd would silently file the note against
    # wherever this happened to run rather than against nothing.
    if not cwd:
        return ""
    try:
        current = os.path.abspath(cwd)
    except (OSError, ValueError):
        return ""
    if not os.path.isdir(current):
        return ""
    for _ in range(MAX_ANCESTORS):
        try:
            if os.path.exists(os.path.join(current, ".git")):
                return current
        except OSError:
            return ""
        parent = os.path.dirname(current)
        if parent == current:
            return ""
        current = parent
    return ""


def _read_bounded(path):
    """`(text, truncated)` — a bounded head plus a bounded tail."""
    try:
        size = os.path.getsize(path)
    except OSError:
        return "", False
    try:
        with open(path, "rb") as handle:
            if size <= HEAD_BYTES + TAIL_BYTES:
                return handle.read().decode("utf-8", "replace"), False
            head = handle.read(HEAD_BYTES)
            handle.seek(size - TAIL_BYTES)
            tail = handle.read(TAIL_BYTES)
    except OSError:
        return "", False
    # Drop the partial line each bound lands in, so no half-record is parsed.
    head = head[:head.rfind(b"\\n") + 1]
    tail = tail[tail.find(b"\\n") + 1:]
    return (head + b"\\n" + tail).decode("utf-8", "replace"), True


def extract_prompts(transcript_path):
    """`(prompts, truncated)` — the user's own messages, oldest first.

    Only `type == "user"` records, and only their text. Tool results arrive as
    user-role records too and are not something the user said.
    """
    text, truncated = _read_bounded(transcript_path)
    prompts = []
    for line in text.splitlines():
        if not line or line.startswith("{") is False:
            continue
        if "\\"user\\"" not in line:
            continue
        try:
            record = json.loads(line)
        except ValueError:
            continue
        if record.get("type") != "user":
            continue
        content = (record.get("message") or {}).get("content")
        said = ""
        if isinstance(content, str):
            said = content
        elif isinstance(content, list):
            parts = [b.get("text", "") for b in content
                     if isinstance(b, dict) and b.get("type") == "text"]
            said = "\\n".join(p for p in parts if p)
        said = said.strip()
        if said:
            prompts.append(said[:MAX_PROMPT_CHARS])
    if len(prompts) > MAX_PROMPTS:
        prompts = prompts[-MAX_PROMPTS:]
        truncated = True
    return prompts, truncated


def _load(path):
    """Existing note, or a fresh one. A malformed note is never replaced."""
    if not os.path.isfile(path):
        return {"version": NOTE_VERSION, "sessions": []}, True
    try:
        with open(path, encoding="utf-8") as handle:
            data = json.load(handle)
    except (OSError, ValueError):
        return None, False
    if not isinstance(data, dict) or not isinstance(data.get("sessions"), list):
        return None, False
    return data, True


def _write_atomic(path, data):
    directory = os.path.dirname(path)
    fd, tmp = tempfile.mkstemp(dir=directory, prefix=".note_", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(data, handle, indent=2)
        os.replace(tmp, path)
    except OSError:
        try:
            if os.path.exists(tmp):
                os.remove(tmp)
        except OSError:
            pass


def record(payload):
    """The whole job. Returns the path written, or "" — fail open throughout."""
    root = project_root(payload.get("cwd") or "")
    if not root:
        return ""
    prompts, truncated = extract_prompts(payload.get("transcript_path") or "")
    if not prompts:
        return ""

    directory = os.path.join(root, ".claude")
    try:
        os.makedirs(directory, exist_ok=True)
    except OSError:
        return ""
    path = os.path.join(directory, NOTE_BASENAME)

    data, ok = _load(path)
    if not ok:
        return ""          # unreadable or malformed: leave it exactly as it is

    entry = {
        "session_id": payload.get("session_id") or "",
        "ended_at": payload.get("_now") or _now(),
        "cwd": payload.get("cwd") or "",
        "prompts": prompts,
        "truncated": bool(truncated),
    }
    sessions = [s for s in data["sessions"]
                if s.get("session_id") != entry["session_id"]]
    sessions.append(entry)
    data["sessions"] = sessions[-MAX_SESSIONS:]
    data["version"] = NOTE_VERSION
    _write_atomic(path, data)
    return path


def _now():
    import datetime

    return datetime.datetime.now().astimezone().isoformat(timespec="seconds")


def main():
    """Fail open, always. A note is never worth costing somebody a session."""
    try:
        payload = json.loads(sys.stdin.read() or "{}")
        if isinstance(payload, dict):
            record(payload)
    except Exception:
        return


if __name__ == "__main__":
    main()
'''


SPEC = claude_hooks.HookSpec(
    marker=HOOK_MARKER,
    version=HOOK_VERSION,
    event="Stop",
    matcher="",              # Stop is not a tool event
    basename=SCRIPT_BASENAME,
    body=_HOOK_BODY,
)


def render_hook_script() -> str:
    return SPEC.script


def default_script_path() -> str:
    return claude_hooks.default_script_path(SPEC)


def installed_state(settings_path: str = "",
                    script_path: str = "") -> "tuple[str, str]":
    return claude_hooks.installed_state(SPEC, settings_path, script_path)


def install(python_exe: str = "", settings_path: str = "",
            script_path: str = "") -> "tuple[bool, str, list]":
    return claude_hooks.install(SPEC, python_exe, settings_path, script_path)


def uninstall(settings_path: str = "",
              script_path: str = "") -> "tuple[bool, str, list]":
    """OFF means gone: the owned entry AND the script, so no audit misreads it."""
    return claude_hooks.uninstall(SPEC, settings_path, script_path)


def note_path(project_root: str) -> str:
    return os.path.join(project_root or "", ".claude", NOTE_BASENAME)


def read_note(project_root: str) -> "dict | None":
    """The note for a project, or None. Read-only; consumers live elsewhere.

    Phase C's grounding imports this. The dependency runs one way on purpose —
    a guard test forbids this module importing anything that drafts.
    """
    path = note_path(project_root)
    if not os.path.isfile(path):
        return None
    try:
        with open(path, encoding="utf-8") as handle:
            data = json.load(handle)
    except (OSError, ValueError):
        return None
    if not isinstance(data, dict) or not isinstance(data.get("sessions"), list):
        return None
    return data


def predicate_module():
    """Import the rendered script, so tests exercise the deployed logic itself."""
    import importlib.util
    import tempfile

    directory = os.path.join(tempfile.gettempdir(), "tokensave-session-note-src")
    os.makedirs(directory, exist_ok=True)
    text = render_hook_script()
    digest = claude_hooks.script_fingerprint(text)[:16]
    path = os.path.join(directory, "note_%s.py" % digest)
    if not os.path.isfile(path):
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(text)
    spec = importlib.util.spec_from_file_location("tokensave_session_note", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module
