"""test_scaffold — Generate starter pytest files from per-style templates (v4.13).

Powers Test Manager Tab 4. Pick a ``src/`` file + a template kind, get
a ``tests/test_<basename>.py`` with the right fixture imports + a
couple of placeholder test functions for the user to fill in.

Templates (modelled on the v4.12 test files):

* ``pure_helper``       — single-purpose helpers with no I/O. Template
                          mirrors ``tests/test_doc_grounding.py``: plain
                          ``def test_*`` functions, no fixtures.
* ``subprocess_helper`` — subprocess-bound helpers (git/npm/codegraph).
                          Template mirrors ``tests/test_install_codegraph.py``:
                          ``mocker.patch("module.subprocess.run", ...)`` with
                          argv assertions.
* ``dialog_tk``         — ``tk.Toplevel`` dialogs. Template mirrors
                          ``tests/test_dialog_checks.py``: ``@pytest.mark.tk``,
                          uses ``tk_root`` + ``mock_config`` + ``mocker``.
* ``blank``             — minimal pytest file with conftest imports + one
                          stub test. Use for anything that doesn't fit
                          the three patterns above.

All templates include TODO comments at the points where the user fills
in implementation. Generated files COMPILE and PASS pytest immediately
(stub tests are ``assert True``) so the user gets fast green feedback
before customising.

Pure module — no Tk, no subprocess, no global state.
"""
from __future__ import annotations

import os
from typing import Literal


TemplateKind = Literal["pure_helper", "subprocess_helper", "dialog_tk", "blank"]

TEMPLATES: tuple[TemplateKind, ...] = (
    "pure_helper", "subprocess_helper", "dialog_tk", "blank"
)


# ── Source-path → module-import string ───────────────────────────────────

def _source_to_module(source_path: str, project_root: str) -> tuple[str, str]:
    """Map ``src/helpers/foo.py`` → ``("helpers.foo", "foo")``.

    Returns ``(import_path, basename_without_ext)``. Used by every
    template to build the right ``from <import_path> import ...`` line.
    """
    src_root = os.path.join(project_root, "src")
    rel = os.path.relpath(source_path, src_root).replace("\\", "/")
    parts = rel[:-len(".py")].split("/")
    return ".".join(parts), parts[-1]


# ── Templates ────────────────────────────────────────────────────────────

_PURE_HELPER_TEMPLATE = '''\
"""tests/{test_filename} — pure-logic helpers from {import_path}.

Generated by Test Manager (v4.13) scaffold. Replace placeholders with
real assertions covering the helper's contract.

Fixtures: none needed — these are pure functions with no I/O.
"""
from __future__ import annotations

import pytest

# TODO: import the actual symbols you want to test:
#     from {import_path} import some_function, AnotherClass
# (The placeholder import below keeps the generated file syntactically
# valid until you customise it.)
import {import_path} as _module_under_test  # noqa: F401


# ── Happy-path tests ─────────────────────────────────────────────────────

def test_TODO_basic_happy_path():
    """TODO: assert the function returns the expected value on typical input."""
    # result = some_function(...)
    # assert result == expected_value
    assert True   # placeholder — replace


# ── Edge-case tests ──────────────────────────────────────────────────────

def test_TODO_empty_input():
    """TODO: assert behaviour on empty / None / boundary inputs."""
    assert True   # placeholder


def test_TODO_unicode_or_special_chars():
    """TODO: assert behaviour on tricky inputs (unicode, whitespace, etc.)."""
    assert True   # placeholder


# ── Error-path tests ─────────────────────────────────────────────────────

def test_TODO_invalid_input_raises():
    """TODO: pytest.raises(SomeError) on malformed input."""
    # with pytest.raises(ValueError):
    #     some_function(invalid_input)
    assert True   # placeholder
'''


_SUBPROCESS_HELPER_TEMPLATE = '''\
"""tests/{test_filename} — subprocess-bound helpers from {import_path}.

Generated by Test Manager (v4.13) scaffold. Mocks ``subprocess.run`` /
``subprocess.Popen`` at the IMPORT SITE (G-E) — never globally — so
pytest's own subprocess infrastructure stays intact.

Pattern: assert argv shape rather than running the real command.
This is safety-critical for destructive commands like ``git push --force``,
``git filter-repo``, ``npm uninstall -g``, etc.
"""
from __future__ import annotations

from types import SimpleNamespace

import pytest

# TODO: import the actual functions you want to test:
#     from {import_path} import install_X, uninstall_X
# (The placeholder import below keeps the file syntactically valid.)
import {import_path} as _module_under_test  # noqa: F401


def _proc(rc: int = 0, stdout: str = "", stderr: str = "") -> SimpleNamespace:
    """Build a fake CompletedProcess for mocker.patch return values."""
    return SimpleNamespace(returncode=rc, stdout=stdout, stderr=stderr)


# ── Argv-construction tests (the safety-critical assertions) ─────────────

def test_TODO_constructs_correct_argv(tmp_path, mocker):
    """TODO: assert the command argv matches the expected shape exactly."""
    mock_run = mocker.patch(
        # IMPORTANT: patch at the IMPORT SITE, not globally:
        "{import_path}.subprocess.run",
        return_value=_proc(rc=0, stdout="ok"),
    )
    # TODO: call the helper under test
    # some_helper(str(tmp_path), "arg1", "arg2")

    # TODO: assert the exact argv
    # cmd = mock_run.call_args[0][0]
    # assert cmd == ["expected", "command", "shape"]
    assert mock_run is not None   # placeholder — replace


# ── Return-value tests ───────────────────────────────────────────────────

def test_TODO_returns_true_on_rc_zero(tmp_path, mocker):
    """TODO: helper returns (True, ...) when the subprocess exits 0."""
    mocker.patch("{import_path}.subprocess.run",
                 return_value=_proc(rc=0))
    # ok, _ = some_helper(...)
    # assert ok is True
    assert True   # placeholder


def test_TODO_returns_false_on_rc_nonzero(tmp_path, mocker):
    """TODO: helper returns (False, error_msg) when the subprocess fails."""
    mocker.patch("{import_path}.subprocess.run",
                 return_value=_proc(rc=1, stderr="permission denied"))
    # ok, msg = some_helper(...)
    # assert ok is False
    # assert "permission denied" in msg
    assert True   # placeholder
'''


_DIALOG_TK_TEMPLATE = '''\
"""tests/{test_filename} — {import_path} dialog tests (Tk-marked).

Generated by Test Manager (v4.13) scaffold. Uses the v4.12 conftest.py
fixtures: ``tk_root`` (session-scoped), ``mock_config``, ``patch_after``
(for dialogs with worker threads that call ``self.after``), and
``wait_for`` (event-loop-driving polling).

Marked ``@pytest.mark.tk`` so this file is excluded from the pre-push
hook (no display needed for the headless CI path).
"""
from __future__ import annotations

import pytest

tk = pytest.importorskip("tkinter")

# TODO: import the actual dialog class you want to test:
#     from {import_path} import SomeDialog
# (The placeholder import keeps the file syntactically valid.)
import {import_path} as _module_under_test  # noqa: F401

pytestmark = pytest.mark.tk


# ── Construction + initial state ─────────────────────────────────────────

def test_TODO_dialog_constructs(tk_root, mock_config, mocker):
    """TODO: instantiate the dialog without errors; assert key widgets exist."""
    # dialog = SomeDialog(tk_root, mock_config)
    # assert dialog.title() == "Expected Title"
    assert tk_root is not None   # placeholder


def test_TODO_initial_state(tk_root, mock_config, mocker):
    """TODO: assert the dialog renders the expected initial state."""
    # dialog = SomeDialog(tk_root, mock_config)
    # assert str(dialog._some_button.cget("state")) == "normal"
    assert True   # placeholder


# ── Handler behaviour ────────────────────────────────────────────────────

def test_TODO_handler_calls_helper_and_updates_ui(
    tk_root, mock_config, mocker
):
    """TODO: a primary-action handler delegates to the right helper
    and reflects the result in the UI."""
    # mock_helper = mocker.patch("{import_path}.some_helper_function",
    #                              return_value=(True, "done"))
    # dialog = SomeDialog(tk_root, mock_config)
    # dialog._on_primary_action()
    # mock_helper.assert_called_once()
    # assert "done" in dialog._status_label.cget("text")
    assert True   # placeholder


# ── Worker-thread integration (use only if the dialog spawns threads) ────

def test_TODO_worker_thread_completes(
    tk_root, mock_config, mocker, patch_after, wait_for
):
    """TODO: if the dialog spawns a background thread that calls
    ``self.after(0, ...)``, use ``patch_after`` to redirect those calls
    into an AfterHarness (G-A) and ``wait_for`` to poll for completion."""
    # dialog = SomeDialog(tk_root, mock_config)
    # patch_after(dialog)
    # dialog._on_action_that_spawns_worker()
    # wait_for(lambda: mock_config._saved, timeout_s=2.0)
    assert True   # placeholder
'''


_BLANK_TEMPLATE = '''\
"""tests/{test_filename} — pytest scaffold for {import_path}.

Generated by Test Manager (v4.13) scaffold. Replace this docstring and
fill in the placeholder tests with real assertions.
"""
from __future__ import annotations

import pytest

# Common imports you may need:
# from {import_path} import ...
# from types import SimpleNamespace


def test_TODO_first_assertion():
    """TODO: replace with a real test."""
    assert True   # placeholder


def test_TODO_second_assertion(tmp_path):
    """TODO: replace with a real test. tmp_path is a per-test directory."""
    assert tmp_path.is_dir()   # placeholder


def test_TODO_with_mocker(mocker):
    """TODO: replace with a real test using pytest-mock's mocker fixture."""
    # mock_something = mocker.patch("{import_path}.some_function",
    #                                 return_value="mocked")
    assert mocker is not None   # placeholder
'''


_TEMPLATE_MAP: dict[str, str] = {
    "pure_helper":       _PURE_HELPER_TEMPLATE,
    "subprocess_helper": _SUBPROCESS_HELPER_TEMPLATE,
    "dialog_tk":         _DIALOG_TK_TEMPLATE,
    "blank":             _BLANK_TEMPLATE,
}


# ── Test-file path resolution ────────────────────────────────────────────

def _test_filename_for(source_path: str, project_root: str) -> str:
    """Return the conventional ``tests/test_<basename>.py`` filename.

    Mirrors the convention observed in the v4.12 test suite:

      * ``src/helpers/quality_checks.py``  → ``test_quality_checks.py``
      * ``src/dialogs/checks_dialog.py``   → ``test_dialog_checks.py``
      * ``src/dialogs/tool_manager.py``    → ``test_dialog_tool_manager.py``
      * ``src/controllers/help_tab.py``    → ``test_help_tab.py``

    Dialogs get the ``dialog_`` prefix and lose any trailing ``_dialog``
    suffix; helpers and controllers use the plain ``test_<basename>``
    form. Generated files match what ``test_discovery.scan_coverage_gaps``
    will look for, so the source file flips from "✗ no tests" to
    "✓ tested" the moment the user clicks Generate.
    """
    src_root = os.path.join(project_root, "src")
    rel = os.path.relpath(source_path, src_root).replace("\\", "/")
    parts = rel[:-len(".py")].split("/")
    basename = parts[-1]
    if len(parts) >= 2:
        subpkg = parts[-2]
        if subpkg == "dialogs":
            basename_short = basename
            for suffix in ("_dialog",):
                if basename_short.endswith(suffix):
                    basename_short = basename_short[:-len(suffix)]
            return f"test_dialog_{basename_short}.py"
        # Controllers / helpers / etc. — plain form
        basename_short = basename
        for suffix in ("_ctrl",):
            if basename_short.endswith(suffix):
                basename_short = basename_short[:-len(suffix)]
        return f"test_{basename_short}.py"
    return f"test_{basename}.py"


# ── Public API ───────────────────────────────────────────────────────────

def preview_test_file(source_path: str, template: str,
                       project_root: str) -> str:
    """Return the rendered template content as a string.

    Pure — no filesystem write. Powers Tab 4's live preview pane.
    Raises ``ValueError`` for unknown ``template`` kinds.
    """
    if template not in _TEMPLATE_MAP:
        raise ValueError(
            f"unknown template {template!r}; expected one of {TEMPLATES}"
        )
    import_path, _basename = _source_to_module(source_path, project_root)
    test_filename = _test_filename_for(source_path, project_root)
    return _TEMPLATE_MAP[template].format(
        import_path=import_path,
        test_filename=test_filename,
    )


def generate_test_file(project_root: str, source_path: str,
                        template: str) -> tuple[bool, str]:
    """Render and write ``tests/test_<basename>.py`` from *template*.

    Refuses to overwrite an existing test file — the user must delete
    it via Tab 3 (Stale Tests) first. This is intentional: a half-
    written, customised test file should never be silently clobbered.

    Returns ``(ok, message_or_path)``.
    """
    if template not in _TEMPLATE_MAP:
        return False, (
            f"unknown template {template!r}; "
            f"expected one of {TEMPLATES}"
        )
    if not os.path.isfile(source_path):
        return False, f"source file not found: {source_path}"
    tests_dir = os.path.join(project_root, "tests")
    try:
        os.makedirs(tests_dir, exist_ok=True)
    except OSError as exc:
        return False, f"could not create tests/: {exc}"

    out_filename = _test_filename_for(source_path, project_root)
    out_path = os.path.join(tests_dir, out_filename)
    if os.path.exists(out_path):
        return False, (
            f"refusing to overwrite existing test file:\n  {out_path}\n\n"
            "Delete it via Test Manager → Stale Tests tab first."
        )

    content = preview_test_file(source_path, template, project_root)
    try:
        with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)
    except OSError as exc:
        return False, f"could not write {out_path}: {exc}"

    return True, out_path
